name: .Net build and publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore Backend/EcommerceBackend.Application/EcommerceBackend.Application.csproj

      - name: Build
        run: dotnet build Backend/EcommerceBackend.Application/EcommerceBackend.Application.csproj --configuration Release

      - name: Publish
        run: dotnet publish Backend/EcommerceBackend.Application/EcommerceBackend.Application.csproj --configuration Release --output ./publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ecommerce-api      # <-- artifact name
          path: ./publish

  deploy:                          # <-- moved under jobs:
    runs-on: self-hosted   # Windows Server with IIS
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ecommerce-api      # <-- must match upload name
          path: C:\Users\devops-test2\Documents\publish

      - name: Deploy to IIS
        shell: powershell
        run: |
          Import-Module WebAdministration
          # (your deployment script here)
