name: .Net build and publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore 
Backend/EcommerceBackend.Application/EcommerceBackend.Application.csproj

      - name: Build
        run: dotnet build Backend/EcommerceBackend.Application/EcommerceBackend.Application.csproj --configuration Release

      # - name: Test
      #   run: dotnet test

      - name: Publish
        run: dotnet publish Backend/EcommerceBackend.Application/EcommerceBackend.Application.csproj --configuration Release --output ./publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ecommerce-api
          path: ./publish
